### ISSUE TITLE
uknown kwarg on line 74

### ISSUE THREAD

**Issue by jansindl3r** [frankrolf/Rotator#5]
Hi, I have just installed it and it gives me error that on line 74 is an `continuous - unknown kwarg` - *NumberEditText*, commenting it out solved it. I have RF 3.3. Is it something that was compatible in the previous versions of RF? Or is something wrong at my side?

**Comment by frankrolf** [comment]
This happened because I am using the RF 3.4 Beta, which introduced the `NumberEditText` mechanism. I added a simple if/else to check for older versions – please let me know if it works!

**Comment by jansindl3r** [comment]
@frankrolf works well, thanks for this tool!

**Comment by frankrolf** [comment]
Great! :-)
